# Default values for kubernetes 
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: "k8s"
fullnameOverride: "k8s"

image:
  litmus: 
    repository: litmuschaos/ansible-runner
    tag: 1.3.0

  pumba:
    repository: gaiaadm/pumba
    tag: 0.6.5

  powerfulseal:
    repository: store/bloomberg/powerfulseal
    tag: 2.8.0

  chaostoolkit:
    repository: litmuschaos/chaostoolkit
    tag: latest

  md5sumCpuStress:    
    repository: litmuschaos/app-cpu-stress
    tag: latest

  ddMemoryStress:    
    repository: litmuschaos/app-memory-stress
    tag: latest

  linuxStressNG:
    repository: alexeiled/stress-ng
    tag: latest 
